# Puerto del servidor
server:
  port: 8081

# Intervalo de ejecuci칩n de la tarea (ms): 1 hora = 3600000
fetch:
  interval-ms: 3600000

# Clave de NewsAPI.org
newsapi:
  key: a745b7d79af74daaa7fb03a9dada32c2

# Configuraci칩n de InfluxDB
influx:
  url: http://localhost:8086
  database: trendviz

# Configuraci칩n de MongoDB
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/trendvizdb

# Clave de OpenWeatherMap (para m치s adelante)
weather:
  apikey: YOUR_OWM_KEY
